### ISSUE TITLE
Missing UpdateState FabricCall implementation

### ISSUE THREAD

**Issue by anweiss** [hyperledgendary/fabric-chaincode-wasm#11]
Was there some sort of nuance prohibiting one from implementing the "UpdateState" namespace in `FabricCall()`? Or is just a matter of duplicating the "CreateState" implementation for this operation since it ultimately needs to call the same `PutState` method for the update operation?

**Comment by mbwhite** [comment]
No nuance; just not quite got to all the features we want to implement yet ;-)

**Comment by anweiss** [comment]
Ok cool ... will get a PR up for this.

**Comment by jt-nti** [comment]
I think this is done now
